version: "3.8"
services:
    elasticsearch:
        image: elasticsearch:7.17.6
        container_name: elk_elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        restart: always
        environment:
            - "cluster.name=elasticsearch"
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        volumes:
            - D:/DockerRepository/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
            - D:/DockerRepository/elk/elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - elk
            
    kibana:
        image: kibana:7.17.6
        container_name: elk_kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        volumes:
            - D:/DockerRepository/elk/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
        networks:
            - elk
            
    logstash:
        image: logstash:7.17.6
        container_name: elk_logstash
        restart: always
        ports:
            - 4560:4560
        depends_on:
            - elasticsearch
        links:
            - elasticsearch:es
        volumes:
            - D:/DockerRepository/elk/logstash/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf
        networks:
            - elk

networks:
    elk:
        